### ISSUE TITLE
Server crashes trying to get user info when not logged in

### ISSUE THREAD

**Issue by sfiquet** [chingu-voyage3/bears-20#73]
```
events.js:183
      throw er; // Unhandled 'error' event
      ^

TypeError: Cannot read property '_id' of undefined
    at /Users/sylvie/Dev/Chingu/BitHelper/routes/users/users.js:57:24
    at model.Query.<anonymous> (/Users/sylvie/Dev/Chingu/BitHelper/node_modules/mongoose/lib/model.js:4056:16)
    at /Users/sylvie/Dev/Chingu/BitHelper/node_modules/kareem/index.js:273:21
    at /Users/sylvie/Dev/Chingu/BitHelper/node_modules/kareem/index.js:131:16
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickCallback (internal/process/next_tick.js:180:9)
```

It looks like it's accessing `req.user._id` without checking that `req.user` is defined.

**Comment by sfiquet** [comment]
Note: I fixed it in my branch
